### ISSUE TITLE
Angularjs + Event.js = ng-click problem

### ISSUE THREAD

**Issue by marcog83** [mudcube/Event.js#10]
Hi,
I use event.js in conjuntion with fabric.js to manipulate canvas on mobile phone.
As application framework I use angularjs 1.2.7.

I added ng-click directive on anchor element, and that anchor is dinamically added and removed from DOM.

html:
[blockcode]
< a ng-click="doSomething()" href="javascript:void(0)">DO STUFF </a >
[blockcode]

problem:
"doSomething" listener is not executed and each time I remove anchor element this error occurs  

Listener is not a function! [a, "click", Array[1], Object, "remove", true]

I know it's a very generic description, but I can't isolate a piece of code.

![image](https://f.cloud.github.com/assets/4071265/1888135/1b7dea1e-7a09-11e3-8e03-dd46f9076dd9.png)

I attached a screenshot from devtools, I hope it can help

P.S.
I commented this line 

eventManager(this, type, listener, configure, trigger, true);

and uncommented the follow one

handler.call(this, type, listener, useCapture);

Error disapears and listeners are ok now. But actually I don't know what happened :P

**Comment by mudcube** [comment]
Yup, exactly as miacle2k mentioned, turn those two features off and you'll be good to go. I contacted Fabric to let them know they can update to the latest package of Eventjs
