### ISSUE TITLE
Support for IE8

### ISSUE THREAD

**Issue by Kienz** [mudcube/Event.js#12]
`window.getComputedStyle` and `style.getPropertyValue` are not supported in IE <= 8.
You can just use something like that - code is from [fabric.js](https://github.com/kangax/fabric.js/blob/master/src/util/dom_misc.js#L191-206)
```js
var getElementStyle;
if (document.defaultView && document.defaultView.getComputedStyle) {
  getElementStyle = function(element, attr) {
    var style = document.defaultView.getComputedStyle(element, null);
    return style ? style[attr] : undefined;
  };
}
else {
  getElementStyle = function(element, attr) {
    var value = element.style[attr];
    if (!value && element.currentStyle) {
      value = element.currentStyle[attr];
    }
    return value;
  };
}
```

**Comment by mudcube** [comment]
Howdy Kienz, 

I'll make a mention of that on the README. I'm not interested in including a polyfill in the code (as other modules may also require a feature and then you have multiple polyfills filling the same gaps in the browser). 

I recommend to polyfill the browser support for the missing feature instead. In my own projects I use this polyfill: https://github.com/jonathantneal/Polyfills-for-IE8/blob/master/getComputedStyle.js

Which is part of the polyfill.io service (worth checking out)
