### ISSUE TITLE
Gruntfile - should it build Event.js and not the minimised version?

### ISSUE THREAD

**Issue by stodge** [mudcube/Event.js#15]
Forgive me if I don't know what I'm talking about, because I probably don't. Using Gulp, the grunt file (from what I understand) builds Event.min.js. Could or should the gruntfile build Event.js instead, so that the developer can choose to minimise the file using a pipe? I apologise if this makes no sense. Thanks

**Comment by mudcube** [comment]
Hi Stodge, the Gruntfile builds both Event.js and Event.min.js. To use with gulp you'll need to write your own packager—copy the file sources under the concat section in the Gruntfile which you'd like to include in your gulp packager.
